### ISSUE TITLE
0.4.1: pytest is failing in `tests/test_find_dependencies.py::test_no_checks_if_collection_failed` unit

### ISSUE THREAD

**Issue by kloczek** [mrbean-bremen/pytest-find-dependencies#2]
I'm trying to package your module as an rpm package. So I'm using the typical PEP517 based build, install and test cycle used on building packages from non-root account.
- `python3 -sBm build -w`
- install .whl file in </install/prefix>
- run pytest with PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>

Here is pytest output:
```console
n-pytest-find-dependencies-0.4.1-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.12, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /home/tkloczko/rpmbuild/BUILD/pytest-find-dependencies-0.4.1, configfile: setup.cfg, testpaths: tests
plugins: find-dependencies-0.4.1, flaky-3.7.0, freezegun-0.4.2, mock-3.6.1, hypothesis-6.32.1, timeout-2.0.2, subtests-0.5.0
collected 20 items

tests/test_find_dependencies.py ..F.................                                                                                                                 [100%]

================================================================================= FAILURES =================================================================================
___________________________________________________________________ test_no_checks_if_collection_failed ____________________________________________________________________

test_path = <Testdir local('/tmp/pytest-of-tkloczko/pytest-267/test_no_checks_if_collection_failed0')>

    def test_no_checks_if_collection_failed(test_path):
        test_path.makepyfile(
            test_one="""
            def test_a(): pass
            def test_b(): pass
            """
        )
        test_path.makepyfile(
            conftest="""
            def pytest_collection(session):
                session.perform_collect()
                session.testsfailed = 1
            """
        )
        result = test_path.runpytest("--find-dependencies")
        result.assert_outcomes(passed=0, failed=0)
>       result.stdout.fnmatch_lines([
            "*Interrupted: 1 errors during collection*",
            "*no tests ran*"
        ])
E       Failed: nomatch: '*Interrupted: 1 errors during collection*'
E           and: '============================= test session starts =============================='
E           and: 'platform linux -- Python 3.8.12, pytest-6.2.5, py-1.11.0, pluggy-1.0.0'
E           and: 'rootdir: /tmp/pytest-of-tkloczko/pytest-267/test_no_checks_if_collection_failed0, configfile: pytest.ini'
E           and: 'plugins: find-dependencies-0.4.1, flaky-3.7.0, freezegun-0.4.2, mock-3.6.1, hypothesis-6.32.1, timeout-2.0.2, subtests-0.5.0'
E           and: 'collected 2 items'
E           and: 'collected 2 items'
E           and: ''
E           and: '=============================== warnings summary ==============================='
E           and: '../../../../usr/lib/python3.8/site-packages/pytest_freezegun.py:17'
E           and: '../../../../usr/lib/python3.8/site-packages/pytest_freezegun.py:17'
E           and: '../../../../usr/lib/python3.8/site-packages/pytest_freezegun.py:17'
E           and: '../../../../usr/lib/python3.8/site-packages/pytest_freezegun.py:17'
E           and: '  /usr/lib/python3.8/site-packages/pytest_freezegun.py:17: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.'
E           and: "    if LooseVersion(pytest.__version__) < LooseVersion('3.6.0'):"
E           and: ''
E           and: '-- Docs: https://docs.pytest.org/en/stable/warnings.html'
E       fnmatch: '*Interrupted: 1 errors during collection*'
E          with: '!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!'
E       nomatch: '*no tests ran*'
E           and: '============================= 4 warnings in 0.12s =============================='
E       remains unmatched: '*no tests ran*'

/home/tkloczko/rpmbuild/BUILD/pytest-find-dependencies-0.4.1/tests/test_find_dependencies.py:61: Failed
--------------------------------------------------------------------------- Captured stdout call ---------------------------------------------------------------------------
============================= test session starts ==============================
platform linux -- Python 3.8.12, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /tmp/pytest-of-tkloczko/pytest-267/test_no_checks_if_collection_failed0, configfile: pytest.ini
plugins: find-dependencies-0.4.1, flaky-3.7.0, freezegun-0.4.2, mock-3.6.1, hypothesis-6.32.1, timeout-2.0.2, subtests-0.5.0
collected 2 items
collected 2 items

=============================== warnings summary ===============================
../../../../usr/lib/python3.8/site-packages/pytest_freezegun.py:17
../../../../usr/lib/python3.8/site-packages/pytest_freezegun.py:17
../../../../usr/lib/python3.8/site-packages/pytest_freezegun.py:17
../../../../usr/lib/python3.8/site-packages/pytest_freezegun.py:17
  /usr/lib/python3.8/site-packages/pytest_freezegun.py:17: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    if LooseVersion(pytest.__version__) < LooseVersion('3.6.0'):

-- Docs: https://docs.pytest.org/en/stable/warnings.html
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
============================= 4 warnings in 0.12s ==============================
============================================================================= warnings summary =============================================================================
../../../../../usr/lib/python3.8/site-packages/pytest_freezegun.py:17: 40 warnings
  /usr/lib/python3.8/site-packages/pytest_freezegun.py:17: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    if LooseVersion(pytest.__version__) < LooseVersion('3.6.0'):

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================================================================= short test summary info ==========================================================================
FAILED tests/test_find_dependencies.py::test_no_checks_if_collection_failed - Failed: nomatch: '*Interrupted: 1 errors during collection*'
================================================================ 1 failed, 19 passed, 40 warnings in 16.00s ================================================================
```

**Comment by mrbean-bremen** [comment]
Hm, that's due to these freezegun warnings. The test doesn't expect warnings.

**Comment by kloczek** [comment]
OK will try to open the ticket against freezegun :)

PS. Temporary I've added that unit to the --deselect list.

**Comment by mrbean-bremen** [comment]
I can ignore warnings in the relevant tests (e.g. the ones that would change in the resence of warnings), this should fix it.

**Comment by mrbean-bremen** [comment]
You can check with the main branch now.

**Comment by kloczek** [comment]
Actually I just found that I've already done that on another occasion :P 
https://github.com/spulec/freezegun/issues/435

**Comment by mrbean-bremen** [comment]
Yeah, with your frequency of writing issues it's difficult to keep check...

**Comment by kloczek** [comment]
> I can ignore warnings in the relevant tests (e.g. the ones that would change in the presence of warnings), this should fix it.

I think that healthier would be not ignoring that as that freezgun issue affects as well other modules.

**Comment by mrbean-bremen** [comment]
Well, as the warnings are not relevant for these tests (I'm only interested in failed in passed tests), I can as well ignore them.

**Comment by kloczek** [comment]
Remember that testing module A is not only about testing that exact module and it it is also about testing ALL other modules used in test suite. From that point of view it is good to at least keep such warnings visible :)
So visibility .. yes.
However disable warning completely .. please no :)

PS. Will try to check you recent changes shortly.

**Comment by mrbean-bremen** [comment]
Well, I disagree. There will always be conditions (like faulty pytest plugins) that may break the tests, but I'm not interested in testing any arbitrary environment here. Normally, I run the tests in a controlled CI environment, and if that is not possible (like in your case), I will ll try to isolate my tests from any irrelevant (for these tests) environment. Specifically for packaging I have done this a few times to make packaging without test errors possible in some distributions (not with this plugin of course - this is hardly used by anyone and unlikely to be packaged into any distribution).

**Comment by kloczek** [comment]
> Well, I disagree

I can understand your statement formed from single module developer/maintainer point of view.
However that view changes to much broader context when you are entering level up to maintain whole population of the packages :)
All interactions between all packages during the testing processes are really valuable as same as interactions between pytest units reshuffled randomly :)

**Comment by mrbean-bremen** [comment]
True, but that is not the point of unit tests. That would be kind of integration tests, which also make sense, but at another level (probably what you are doing). From my experience with package maintainers I can say that they are usually not interested in that kind of testing, they just want to cleanly package modules the users are interested in.

May I ask what is the goal of all your packaging efforts? I understand you are not maintaining a distribution?

**Comment by kloczek** [comment]
> May I ask what is the goal of all your packaging efforts? I understand you are not maintaining a distribution?

Yes that is true however it is not ready yet to make it publicly available :/
I've started from Fedora on on top of that I have a lot of optimisations, solved issues, build ands testing infrastructure improvements and completely new functionalities on that area.
+12 years ago I've been leading work on some other distribution but that project failed and some time ago I've decided to back to something like that because my eye sometime literally have been bleeding when I've been looking on RH, Fedora and many Debian or Debian based distribution.
Many people do not understand problems of the large scale packages maintenance and in most of the distributions people are working on the scale single or few (only) packages.
Result of that approach is that many people do not see even some issues and it is even VERY hard to explain that something may be issue on that layer.
Working on the past on the sale of few thousands packages I have some unique observations about even necessary tooling to maintain such big number of packages by few (only) people.
Only in smaller group  so called "communication factor" (which is growing with factorial of the people involved in the team) keeps that factor below some threshold which allows to make some valuable observations without possessing kind of SuperPowers :)

**Comment by mrbean-bremen** [comment]
Thanks for the explanation - sounds like an uphill battle to me. But well, as long as you've got the time and the energy...

**Comment by kloczek** [comment]
All battles are uphil :)
All changes requires some energy .. physics is bitch :)

**Comment by mrbean-bremen** [comment]
What about this issue - can we close it? I have added the warning suppression to main, but you won't need that, as I understand, right?

**Comment by kloczek** [comment]
I think .. yes we can close that :)
