### ISSUE TITLE
[BUG] Doesn't work with files/directories passed in the command line

### ISSUE THREAD

**Issue by ElPicador** [mrbean-bremen/pytest-find-dependencies#3]
## Description

Running `pytest --find-dependencies directory` or `pytest --find-dependencies test_a.py test_b.py` doesn't limit find dependencies to only the directory/files passed in the command line.

Why is this useful? 
We have a monorepo with multiple projects. And we want to run find dependencies only on some tests/subfolder. And for now it doesn't work.

## How to reproduce
I tried to write a test to reproduce the issue (only with files though)

```
def test_filenames(test_path):
    test_path.makepyfile(
        test_one="""
        def test_a(): pass
        def test_b(): pass
        """,
        test_two="""
        def test_c(): pass
        def test_d(): pass
        """,
        test_three="""
        def test_e(): pass
        def test_f(): pass
        """
    )

    result = test_path.runpytest("--find-dependencies", "test_one.py", "test_three.py")
    result.assert_outcomes(passed=4, failed=0)
    result.stdout.fnmatch_lines([
        "test_one.py::test_a PASSED",
        "test_one.py::test_b PASSED",
        "test_one.py::test_e PASSED",
        "test_one.py::test_f PASSED",
    ])
```

**Comment by mrbean-bremen** [comment]
Thanks, I will have a look later. Good to know that somebody besides myself is using this!

**Comment by mrbean-bremen** [comment]
Actually it should work as is, I just tested it. If I run your test above, I get something like:
```
============================= test session starts =============================
...
plugins: find-dependencies-0.4.0, flaky-3.7.0, pyfakefs-4.5.0, dependency-0.5.1, freezegun-0.4.2, mock-3.6.1, order-1.0.0
collecting ... collected 4 items

=====================================================
Run dependency analysis for 4 tests.
Executed 8 tests in 2 test runs.
No dependent tests found.
=====================================================
```
I made a few more tests, and they all behaved as expected, e.g. tested only the modules or directories given on the commandline.
The tests themselves are not shown intentionally to reduce the output (with many tests it will be overwhelming, and we are not interested in the actual tests in this case, so the tests are run with -q), so your test example will not pass. I could add an option to change this, but I think this is generally not needed if you are only interested in dependent tests.

Can you show me the output you get in your case? Maybe you have some other enviroment? Right now I have no idea how this could happen.

**Comment by mrbean-bremen** [comment]
Ok, thank you for the information! The real bug is obviously the bogus dependency on not included tests - that looks really strange, I will have a look at that, I think this should be easily reproducible. 

As for your test: it won't work this way. `assert_outcomes` will not work correctly in this case due to the fact that the tests are run in separate processes (this is done to avoid dependencies between test runs) and not seen by the test. The test output also does not contain the test names, as I wrote above - if you check the other tests, you will see that they only test the final outcome (which is correct in your case). You can also see that 4 tests are collected as expected.

**Comment by mrbean-bremen** [comment]
I understood the problem and will merge a fix in a minute. If you want, you can check the version from the main branch.
I found another problem (too many tests executed) that I want to understand and fix before making another release, though that may take some time. 
Thanks again for the report and the investigation!

**Comment by ElPicador** [comment]
Your fix works 🥳 Thanks a bunch!

But now I have another issue 🙈. I have failing tests but it doesn't result in a failure of the run of `pytest`. I'll investigate

**Comment by ElPicador** [comment]
Closing as it's fixed
