### ISSUE TITLE
[Bug/Feature]: Non 0 exit code when dependencies are found

### ISSUE THREAD

**Issue by ElPicador** [mrbean-bremen/pytest-find-dependencies#4]
## Description

When dependencies are found `pytest` returns a non failing exit code: it returns the code `0`). This makes a run in the CI non failing. 

I think it would make more sense for `pytest-find-dependencies` to fail when it finds dependencies between tests.

My dream use case would be to run `pytest-find-dependencies` once per day during the night, and have a failing CI job if it finds any dependent tests

## How to reproduce

We see it here ⬇️ 

![Screenshot 2022-01-14 at 11 00 30](https://user-images.githubusercontent.com/16667/149496845-5d0e0577-63aa-4a9f-9426-f59a3d379d55.png)

**Comment by mrbean-bremen** [comment]
Good point, that makes sense.

**Comment by mrbean-bremen** [comment]
Shall work in main now.

**Comment by mrbean-bremen** [comment]
A new pypi release is out which has this integrated (plus other fixes). 
Closing, feel free to reopen if it does not work for you.
